# Generated by Django 5.1.7 on 2025-03-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_description', models.TextField()),
                ('fund_nav', models.FloatField()),
                ('fund_creation_date', models.DateField()),
                ('fund_performance', models.FloatField(help_text='Performance in percentage')),
                ('fund_manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_funds',
            },
        ),
    ]
