# Generated by Django 5.1.7 on 2025-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentfund',
            name='fund_manager',
            field=models.CharField(max_length=255),
        ),
    ]
